### PR TITLE
Refactoring to accept custom SSL contexts in ConnectionSettings

### PR DESCRIPTION
**Pull request by etspaceman**

### CODE REVIEW

**Comment by etspaceman** [comment]
Failed travis build due to a bad download from SBT. This PR invokes no changes on the build. @LGLO

**Comment by mkiedys** [comment]
LGTM

**Comment by etspaceman** [comment]
Hi @mkiedys will this make it into a release soon?

**Comment by mkiedys** [comment]
Released in 1.1.3.

**Pull request merged**
