### PR TITLE
Separate, non temporary, channel allows full recovery

### PR DESCRIPTION
**Pull request by LGLO**
Formerly, when channels were opened just for declaring some entity, channel was closed during connection recovery what prevented successful entities recovery.

### CODE REVIEW

**Comment by mkiedys** [comment]
Can you explain what this is doing? Why `adminChannel` is never closed?

**Comment by LGLO** [comment]
There is connection with auto-recovery.
When connection recovers it tries to recover channels, then entities and then consumers.
When you create channel, use it to declare some entity and then close it, then during entity recovery given channel is closed with code 200.

That is why I added one (lazy) channel. If your app does some admin work, then I will have this channel opened. When connection recovers, then entities are recovered.

What do you think about separate trait Admin for all this admin functionality? One could use `RabbitConnection` or `RabbitConnectionWithAdmin`?

**Comment by mkiedys** [comment]
Lech, can you rebase this pull request?

**Comment by notvitor** [comment]
Hi guys!

Can you guys rebase this?

Please and thank you!

-V

**Comment by LGLO** [comment]
I'll fix #33, update dependencies and will take care of this tomorrow.

**Pull request merged**
