### PR TITLE
Allow to use any SSL protocol

### PR DESCRIPTION
**Pull request by mkiedys**
This pull request allows to set other protocol than TLSv1.2 while enabling SSL in the client.

@zackangelo, @aleachjr let me know if this will work for you.

Related: #17, #18

### CODE REVIEW

**Comment by zackangelo** [comment]
lgtm :+1:

**Comment by aleachjr** [comment]
@mkiedys thanks again for the quick turnaround. Please let me know when we can pull this down!

**Comment by zackangelo** [comment]
@mkiedys would you mind pushing up a new snapshot release to sonatype?

**Comment by mkiedys** [comment]
This is in progress. I will let you know once released.

**Pull request merged**
