### PR TITLE
Reorganized scaladoc for ConnectionSettings + README

### PR DESCRIPTION
**Pull request by LGLO**
I've moved scaladoc string so generated documentation contains these comments.
This if my first part for #24

### CODE REVIEW

**Comment by LGLO** [comment]
These JDK7 builds have failed last few times also.

**Comment by mkiedys** [comment]
> These JDK7 builds have failed last few times also.

Bug in JDK6/7: https://github.com/travis-ci/travis-ci/issues/5227

**Comment by mkiedys** [comment]
@LGLO Why you merged this pull request?

**Comment by mkiedys** [comment]
Reverted.

**Comment by mkiedys** [comment]
Rules:

1) nothing goes to master without my approval
2) no merges in general - only rebase with linear history
3) small change and many commits: squash first
4) follow same git commit message style

**Comment by LGLO** [comment]
Is it possible we talk via sth more private and instant than github
comments? My email: lech.glowiak@scalac.io or skype: lech.glowiak or
twitter @LechGlowiak ?

2016-01-11 15:44 GMT+01:00 Michał Kiędyś <notifications@github.com>:

**Pull request merged**
